apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kubeapp
  labels:
    app: backend
    tier: logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: logic
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kubeapp
  labels:
    app: backend
    tier: logic
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080