apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: kubeapp
  labels:
    app: db
    tier: database
    role: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: database
        role: primary
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "exampledb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "example"
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: kubeapp
  labels:
    app: db
    tier: database
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432