---
- name: Deploy Three-Tier Application
  hosts: k8s
  tasks:
    # Build Docker images
    - name: Build backend Docker image
      command: docker build -t backend:latest /home/vagrant/project/backend

    - name: Build frontend Docker image
      command: docker build -t frontend:latest /home/vagrant/project/frontend

    - name: Create kubeapp namespace
      shell: |
        kubectl get namespace kubeapp || kubectl create namespace kubeapp

    # Apply Kubernetes manifests
    - name: Apply database deployment
      command: kubectl apply -f /home/vagrant/project/kubernetes/db-deployment.yml --namespace=kubeapp

    - name: Wait for database to be ready
      command: kubectl wait --for=condition=ready pod -l app=db --timeout=120s --namespace=kubeapp

    - name: Apply backend deployment
      command: kubectl apply -f /home/vagrant/project/kubernetes/backend-deployment.yml --namespace=kubeapp

    - name: Apply frontend deployment
      command: kubectl apply -f /home/vagrant/project/kubernetes/frontend-deployment.yml --namespace=kubeapp

    # Verify deployment
    - name: Check pod status
      command: kubectl get pods --namespace=kubeapp

    - name: Check services
      command: kubectl get services --namespace=kubeapp